In [223]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB,GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [19]:
dataset = pd.read_csv('train.csv')

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [20]:
#checking for null values in dataset

dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [25]:
label_encoder = preprocessing.LabelEncoder()

encoded_sex = label_encoder.fit_transform(dataset['Sex'])

encoded_embarked = label_encoder.fit_transform(dataset['Embarked'])

In [26]:
dataset['Sex'] = pd.DataFrame(encoded_sex)

dataset['Embarked'] = pd.DataFrame(encoded_embarked)

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [33]:
# Spitting dataset on basis of dependent & independent columns

y = dataset['Survived']
x = dataset.drop(["Survived","Name","Ticket","Cabin","PassengerId"],axis=1)

In [36]:
x.count()

Pclass      889
Sex         889
Age         889
SibSp       889
Parch       889
Fare        889
Embarked    889
dtype: int64

In [41]:
# spliting up test & train dataset

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state =2)

In [45]:
X_train.count()

Pclass      622
Sex         622
Age         622
SibSp       622
Parch       622
Fare        622
Embarked    622
dtype: int64

In [42]:
y_train.count()

622

In [64]:
from sklearn.naive_bayes import *

clf = BernoulliNB()

y_pred = clf.fit(X_train,y_train).predict(X_test)

In [65]:
accuracy_score(y_test,y_pred,normalize=True)

0.8314606741573034

In [66]:
#Total records = 267
#correct = 150 + 72 = 222
#incorrect = 25 + 20 = 45
#accuracy = 0.8314606741573034 222/267

confusion_matrix(y_test,y_pred)

array([[150,  20],
       [ 25,  72]], dtype=int64)

In [69]:
df2 = dataset.drop(["Name","Ticket","Cabin","PassengerId"],axis=1)

In [94]:
df3 = df2.copy()

In [225]:
x = pd.DataFrame()
y = pd.DataFrame()


rcol = ['Pclass', 'Sex',  'SibSp', 'Parch','Embarked']


for i in range(len(rcol)):
    clf = BernoulliNB()
    x = df3.drop(rcol[i],axis=1)
    y = df3[rcol[i]]
    X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state =2)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(rcol[i])
    print(accuracy_score(y_test,y_pred,normalize=True))
    print(confusion_matrix(y_test,y_pred))

Pclass
0.5468164794007491
[[ 19   3  38]
 [ 11   3  53]
 [ 14   2 124]]
Sex
0.7752808988764045
[[ 47  44]
 [ 16 160]]
SibSp
0.6891385767790262
[[167  25   0   0   0   0   0]
 [ 31  17   0   0   0   0   0]
 [  5   7   0   0   0   0   0]
 [  4   3   0   0   0   0   0]
 [  2   2   0   0   0   0   0]
 [  0   1   0   0   0   0   0]
 [  1   2   0   0   0   0   0]]
Parch
0.7715355805243446
[[196  13   0   0   0]
 [ 21  10   0   0   0]
 [ 19   6   0   0   0]
 [  0   1   0   0   0]
 [  1   0   0   0   0]]
Embarked
0.7902621722846442
[[  0   0  42]
 [  0   0  14]
 [  0   0 211]]
